language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t bala/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run bala/react-test npm test -- --coverage

after_success:
  - docker build -t bala0408/multi-client ./client
  - docker build -t bala0408/multi-nginx ./nginx
  - docker build -t bala0408/multi-server ./server
  - docker build -t bala0408/multi-worker ./worker
  #Login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password stdin
  # Push the imagaes to Docker
  - docker push bala0408/multi-client
  - docker push bala0408/multi-nginx 
  - docker push bala0408/multi-server
  - docker push bala0408/multi-worker






